import Foundation

extension ParamsBuilder {
    static func buildPackedParams(from config: ResolvedRenderConfig) -> PackedParams {
        var visibleFlags: UInt32 = 0
        if config.diskPhysicsModeID == 3 && config.visibleModeEnabled && config.visibleExpressiveMode {
            visibleFlags |= 1
        }

        return PackedParams(
            width: UInt32(config.width),
            height: UInt32(config.height),
            fullWidth: UInt32(config.width),
            fullHeight: UInt32(config.height),
            offsetX: 0,
            offsetY: 0,
            camPos: config.camPos,
            planeX: config.planeX,
            planeY: config.planeY,
            z: config.z,
            d: config.d,
            rs: Float(config.rsD),
            re: Float(config.reD),
            he: Float(config.heD),
            M: Float(config.M),
            G: Float(config.G),
            c: Float(config.c),
            k: Float(config.k),
            h: Float(config.hArg),
            maxSteps: Int32(config.maxStepsArg),
            eps: 1e-5,
            metric: config.metricArg,
            spin: Float(config.spinArg),
            kerrSubsteps: Int32(config.kerrSubstepsArg),
            kerrTol: Float(config.kerrTolArg),
            kerrEscapeMult: Float(config.kerrEscapeMultArg),
            kerrRadialScale: Float(config.kerrRadialScaleArg),
            kerrAzimuthScale: Float(config.kerrAzimuthScaleArg),
            kerrImpactScale: Float(config.kerrImpactScaleArg),
            diskFlowTime: Float(config.diskFlowTimeArg),
            diskOrbitalBoost: Float(config.diskOrbitalBoostArg),
            diskRadialDrift: Float(config.diskRadialDriftArg),
            diskTurbulence: Float(config.diskTurbulenceArg),
            diskOrbitalBoostInner: Float(config.diskOrbitalBoostInnerArg),
            diskOrbitalBoostOuter: Float(config.diskOrbitalBoostOuterArg),
            diskRadialDriftInner: Float(config.diskRadialDriftInnerArg),
            diskRadialDriftOuter: Float(config.diskRadialDriftOuterArg),
            diskTurbulenceInner: Float(config.diskTurbulenceInnerArg),
            diskTurbulenceOuter: Float(config.diskTurbulenceOuterArg),
            diskFlowStep: Float(config.diskFlowStepArg),
            diskFlowSteps: Float(config.diskFlowStepsArg),
            diskAtlasMode: config.diskAtlasEnabled ? 1 : 0,
            diskAtlasWidth: UInt32(config.diskAtlasWidth),
            diskAtlasHeight: UInt32(config.diskAtlasHeight),
            diskAtlasWrapPhi: config.diskAtlasWrapPhi,
            diskAtlasTempScale: Float(config.diskAtlasTempScaleArg),
            diskAtlasDensityBlend: Float(config.diskAtlasDensityBlendArg),
            diskAtlasVrScale: Float(config.diskAtlasVrScaleArg),
            diskAtlasVphiScale: Float(config.diskAtlasVphiScaleArg),
            diskAtlasRNormMin: Float(config.diskAtlasRMin),
            diskAtlasRNormMax: Float(config.diskAtlasRMax),
            diskAtlasRNormWarp: Float(config.diskAtlasRWarp),
            diskNoiseModel: config.diskNoiseModel,
            diskMdotEdd: Float(config.diskMdotEddArg),
            diskRadiativeEfficiency: Float(config.diskRadiativeEfficiencyArg),
            diskPhysicsMode: config.diskPhysicsModeID,
            diskPlungeFloor: Float(config.diskPlungeFloorArg),
            diskThickScale: Float(config.diskThickScaleArg),
            diskColorFactor: Float(config.diskColorFactorArg),
            diskReturningRad: Float(config.diskReturningRadArg),
            diskPrecisionTexture: Float(config.diskPrecisionTextureArg),
            diskCloudCoverage: Float(config.diskCloudCoverageArg),
            diskCloudOpticalDepth: Float(config.diskCloudOpticalDepthArg),
            diskCloudPorosity: Float(config.diskCloudPorosityArg),
            diskCloudShadowStrength: Float(config.diskCloudShadowStrengthArg),
            diskReturnBounces: UInt32(config.diskReturnBouncesArg),
            diskRTSteps: UInt32(config.diskRTStepsArg),
            diskScatteringAlbedo: Float(config.diskScatteringAlbedoArg),
            diskRTPad: 0,
            diskVolumeMode: config.diskVolumeEnabled ? 1 : 0,
            diskVolumeR: UInt32(config.diskVolumeR),
            diskVolumePhi: UInt32(config.diskVolumePhi),
            diskVolumeZ: UInt32(config.diskVolumeZ),
            diskVolumeRNormMin: Float(config.diskVolumeRMin),
            diskVolumeRNormMax: Float(config.diskVolumeRMax),
            diskVolumeZNormMax: Float(config.diskVolumeZMax),
            diskVolumeTauScale: Float(config.diskVolumeTauScaleArg),
            diskVolumeFormat: config.diskVolumeFormatArg,
            diskVolumeR0: UInt32(config.diskVolumeR),
            diskVolumePhi0: UInt32(config.diskVolumePhi),
            diskVolumeZ0: UInt32(config.diskVolumeZ),
            diskVolumeR1: UInt32(config.diskVolumeR),
            diskVolumePhi1: UInt32(config.diskVolumePhi),
            diskVolumeZ1: UInt32(config.diskVolumeZ),
            diskNuObsHz: Float(config.diskNuObsHzArg),
            diskGrmhdDensityScale: Float(config.diskGrmhdDensityScaleArg),
            diskGrmhdBScale: Float(config.diskGrmhdBScaleArg),
            diskGrmhdEmissionScale: Float(config.diskGrmhdEmissionScaleArg),
            diskGrmhdAbsorptionScale: Float(config.diskGrmhdAbsorptionScaleArg),
            diskGrmhdVelScale: Float(config.diskGrmhdVelScaleArg),
            diskGrmhdDebugView: config.diskGrmhdDebugID,
            diskPolarizedRT: (config.diskPhysicsModeID == 3 && config.diskPolarizedRTEnabled) ? 1 : 0,
            diskPolarizationFrac: Float(config.diskPolarizationFracArg),
            diskFaradayRotScale: Float(config.diskFaradayRotScaleArg),
            diskFaradayConvScale: Float(config.diskFaradayConvScaleArg),
            visibleMode: (config.diskPhysicsModeID == 3 && config.visibleModeEnabled) ? 1 : 0,
            visibleSamples: UInt32(config.visibleSamplesArg),
            visibleTeffModel: config.visibleTeffModelID,
            visiblePad0: visibleFlags,
            visibleTeffT0: Float(config.visibleTeffT0Arg),
            visibleTeffR0: Float(config.visibleTeffR0Meters),
            visibleTeffP: Float(config.visibleTeffPArg),
            visiblePhotosphereRhoThreshold: Float(config.photosphereRhoThresholdResolved),
            visibleBhMass: Float(config.visibleBhMassArg),
            visibleMdot: Float(config.visibleMdotArg),
            visibleRIn: Float(config.visibleRInMeters),
            visibleKappa: Float(config.visibleKappaArg),
            visibleEmissionModel: config.visibleEmissionModelID,
            visibleEmissionAlpha: Float(config.visibleSynchAlphaArg),
            rayBundleSSAA: config.rayBundleActive ? 1 : 0,
            rayBundleJacobian: config.rayBundleJacobianActive ? 1 : 0,
            rayBundleJacobianStrength: Float(config.rayBundleJacobianStrengthArg),
            rayBundleFootprintClamp: Float(config.rayBundleFootprintClampArg),
            coolAbsorptionMode: (config.diskPhysicsModeID == 3 && config.visibleModeEnabled && config.coolAbsorptionEnabled) ? 1 : 0,
            coolDustToGas: Float(config.coolDustToGasArg),
            coolDustKappaV: Float(config.coolDustKappaVArg),
            coolDustBeta: Float(config.coolDustBetaArg),
            coolDustTSub: Float(config.coolDustTSubArg),
            coolDustTWidth: Float(config.coolDustTWidthArg),
            coolGasKappa0: Float(config.coolGasKappa0Arg),
            coolGasNuSlope: Float(config.coolGasNuSlopeArg),
            coolClumpStrength: Float(config.coolClumpStrengthArg),
            coolAbsorptionPad: 0
        )
    }
}
