import Foundation

enum ParamsBuilderSummary {
    static func renderConfigLine(
        preset: String,
        width: Int,
        height: Int,
        camXFactor: Double,
        camYFactor: Double,
        camZFactor: Double,
        fovDeg: Double,
        rollDeg: Double,
        rcp: Double,
        diskHFactor: Double,
        maxStepsArg: Int,
        metricName: String,
        spinArg: Double,
        kerrSubstepsArg: Int,
        kerrTolArg: Double,
        kerrEscapeMultArg: Double,
        kerrRadialScaleArg: Double,
        kerrAzimuthScaleArg: Double,
        kerrImpactScaleArg: Double,
        diskModelResolved: String,
        diskFlowTimeArg: Double,
        diskOrbitalBoostArg: Double,
        diskRadialDriftArg: Double,
        diskTurbulenceArg: Double,
        diskOrbitalBoostInnerArg: Double,
        diskOrbitalBoostOuterArg: Double,
        diskRadialDriftInnerArg: Double,
        diskRadialDriftOuterArg: Double,
        diskTurbulenceInnerArg: Double,
        diskTurbulenceOuterArg: Double,
        diskFlowStepArg: Double,
        diskFlowStepsArg: Int,
        diskPhysicsModeArg: String,
        diskMdotEddArg: Double,
        diskRadiativeEfficiencyArg: Double,
        diskPlungeFloorArg: Double,
        diskThickScaleArg: Double,
        diskColorFactorArg: Double,
        diskReturningRadArg: Double,
        diskReturnBouncesArg: Int,
        diskRTStepsArg: Int,
        diskScatteringAlbedoArg: Double,
        diskPrecisionTextureArg: Double,
        diskPrecisionCloudsEnabled: Bool,
        diskCloudCoverageArg: Double,
        diskCloudOpticalDepthArg: Double,
        diskCloudPorosityArg: Double,
        diskCloudShadowStrengthArg: Double,
        diskAtlasEnabled: Bool,
        diskAtlasWidth: Int,
        diskAtlasHeight: Int,
        diskAtlasTempScaleArg: Double,
        diskAtlasDensityBlendArg: Double,
        diskAtlasVrScaleArg: Double,
        diskAtlasVphiScaleArg: Double,
        diskAtlasRMin: Double,
        diskAtlasRMax: Double,
        diskAtlasRWarp: Double,
        diskVolumeEnabled: Bool,
        diskVolumeR: Int,
        diskVolumePhi: Int,
        diskVolumeZ: Int,
        diskVolumeRMin: Double,
        diskVolumeRMax: Double,
        diskVolumeZMax: Double,
        diskVolumeTauScaleArg: Double,
        rayBundleEnabled: Bool,
        rayBundleActive: Bool,
        rayBundleJacobianActive: Bool,
        rayBundleJacobianStrengthArg: Double,
        rayBundleFootprintClampArg: Double,
        cameraModelName: String,
        cameraPsfSigmaArg: Float,
        cameraReadNoiseArg: Float,
        cameraShotNoiseArg: Float,
        cameraFlareStrengthArg: Float,
        backgroundModeName: String,
        backgroundStarDensityArg: Float,
        backgroundStarStrengthArg: Float,
        backgroundNebulaStrengthArg: Float,
        tileSize: Int,
        composeGPU: Bool,
        gpuFullCompose: Bool,
        discardCollisionOutput: Bool,
        useLinear32Intermediate: Bool,
        traceHDRDirectMode: String,
        downsampleArg: Int,
        composeAnalysisMode: UInt32
    ) -> String {
        "render config preset=\(preset) \(width)x\(height), cam=(\(camXFactor),\(camYFactor),\(camZFactor))rs, fov=\(fovDeg), roll=\(rollDeg), rcp=\(rcp), diskH=\(diskHFactor)rs, maxSteps=\(maxStepsArg), metric=\(metricName), spin=\(spinArg), kerrSubsteps=\(kerrSubstepsArg), kerrTol=\(kerrTolArg), kerrEscape=\(kerrEscapeMultArg), kerrScale=(\(kerrRadialScaleArg),\(kerrAzimuthScaleArg),\(kerrImpactScaleArg)), diskModel=\(diskModelResolved), diskFlow=(t=\(diskFlowTimeArg),omega=\(diskOrbitalBoostArg),vr=\(diskRadialDriftArg),turb=\(diskTurbulenceArg),omegaIn=\(diskOrbitalBoostInnerArg),omegaOut=\(diskOrbitalBoostOuterArg),vrIn=\(diskRadialDriftInnerArg),vrOut=\(diskRadialDriftOuterArg),turbIn=\(diskTurbulenceInnerArg),turbOut=\(diskTurbulenceOuterArg),dt=\(diskFlowStepArg),steps=\(diskFlowStepsArg)), diskPhysics=(mode=\(diskPhysicsModeArg),mdotEdd=\(diskMdotEddArg),eta=\(diskRadiativeEfficiencyArg),plunge=\(diskPlungeFloorArg),thickScale=\(diskThickScaleArg),fcol=\(diskColorFactorArg),ret=\(diskReturningRadArg),retBounces=\(diskReturnBouncesArg),rtSteps=\(diskRTStepsArg),albedo=\(diskScatteringAlbedoArg),texture=\(diskPrecisionTextureArg),precisionClouds=\(diskPrecisionCloudsEnabled),cloudCoverage=\(diskCloudCoverageArg),cloudTau=\(diskCloudOpticalDepthArg),cloudPorosity=\(diskCloudPorosityArg),cloudShadow=\(diskCloudShadowStrengthArg)), diskAtlas=(enabled=\(diskAtlasEnabled),size=\(diskAtlasWidth)x\(diskAtlasHeight),temp=\(diskAtlasTempScaleArg),density=\(diskAtlasDensityBlendArg),vr=\(diskAtlasVrScaleArg),vphi=\(diskAtlasVphiScaleArg),rMin=\(diskAtlasRMin),rMax=\(diskAtlasRMax),rWarp=\(diskAtlasRWarp)), diskVolume=(enabled=\(diskVolumeEnabled),size=\(diskVolumeR)x\(diskVolumePhi)x\(diskVolumeZ),rMin=\(diskVolumeRMin),rMax=\(diskVolumeRMax),zMax=\(diskVolumeZMax),tauScale=\(diskVolumeTauScaleArg)), rayBundle=(requested=\(rayBundleEnabled),active=\(rayBundleActive),jacobian=\(rayBundleJacobianActive),jacStrength=\(rayBundleJacobianStrengthArg),clamp=\(rayBundleFootprintClampArg)), cameraModel=(name=\(cameraModelName),psf=\(cameraPsfSigmaArg),readNoise=\(cameraReadNoiseArg),shotNoise=\(cameraShotNoiseArg),flare=\(cameraFlareStrengthArg)), background=(mode=\(backgroundModeName),density=\(backgroundStarDensityArg),strength=\(backgroundStarStrengthArg),nebula=\(backgroundNebulaStrengthArg)), tileSize=\(tileSize), io=(composeGPU=\(composeGPU),gpuFullCompose=\(gpuFullCompose),discardCollisions=\(discardCollisionOutput),hdrFileIntermediate=\(useLinear32Intermediate),traceHDRPreference=\(traceHDRDirectMode)), downsample=\(downsampleArg), analysisMode=\(composeAnalysisMode)"
    }

    static func grmhdConfigLine(
        diskVol0PathResolved: String,
        diskVol1PathResolved: String,
        diskNuObsHzArg: Double,
        diskGrmhdDensityScaleArg: Double,
        diskGrmhdBScaleArg: Double,
        diskGrmhdEmissionScaleArg: Double,
        diskGrmhdAbsorptionScaleArg: Double,
        diskGrmhdVelScaleArg: Double,
        diskPolarizedRTEnabled: Bool,
        diskPolarizationFracArg: Double,
        diskFaradayRotScaleArg: Double,
        diskFaradayConvScaleArg: Double,
        diskGrmhdDebugName: String
    ) -> String {
        let grmhdVol0Label = diskVol0PathResolved.isEmpty ? "none" : diskVol0PathResolved
        let grmhdVol1Label = diskVol1PathResolved.isEmpty ? "none" : diskVol1PathResolved
        return "grmhd config vol0=\(grmhdVol0Label), vol1=\(grmhdVol1Label), nuObsHz=\(diskNuObsHzArg), rhoScale=\(diskGrmhdDensityScaleArg), bScale=\(diskGrmhdBScaleArg), jScale=\(diskGrmhdEmissionScaleArg), alphaScale=\(diskGrmhdAbsorptionScaleArg), velScale=\(diskGrmhdVelScaleArg), polarized=\(diskPolarizedRTEnabled), polFrac=\(diskPolarizationFracArg), faradayRot=\(diskFaradayRotScaleArg), faradayConv=\(diskFaradayConvScaleArg), debug=\(diskGrmhdDebugName)"
    }

    static func visibleConfigLine(
        visibleModeEnabled: Bool,
        visiblePolicyName: String,
        visibleSamplesArg: Int,
        visibleTeffModelName: String,
        visibleTeffT0Arg: Double,
        visibleTeffR0RsArg: Double,
        visibleTeffPArg: Double,
        visibleBhMassArg: Double,
        visibleMdotArg: Double,
        visibleRInRsArg: Double,
        photosphereRhoThresholdResolved: Double,
        visibleEmissionModelName: String,
        visibleSynchAlphaArg: Double,
        visibleKappaArg: Double,
        coolAbsorptionEnabled: Bool,
        coolDustToGasArg: Double,
        coolDustKappaVArg: Double,
        coolDustBetaArg: Double,
        coolDustTSubArg: Double,
        coolDustTWidthArg: Double,
        coolGasKappa0Arg: Double,
        coolGasNuSlopeArg: Double,
        coolClumpStrengthArg: Double,
        exposureModeName: String,
        exposureEVArg: Double,
        rayBundleEnabled: Bool,
        rayBundleActive: Bool,
        rayBundleJacobianActive: Bool,
        rayBundleJacobianStrengthArg: Double,
        rayBundleFootprintClampArg: Double
    ) -> String {
        "visible config enabled=\(visibleModeEnabled), policy=\(visiblePolicyName), samples=\(visibleSamplesArg), teffModel=\(visibleTeffModelName), teff=(T0=\(visibleTeffT0Arg),r0Rs=\(visibleTeffR0RsArg),p=\(visibleTeffPArg)), thinDisk=(M=\(visibleBhMassArg),mdot=\(visibleMdotArg),rInRs=\(visibleRInRsArg)), photosphereRho=\(photosphereRhoThresholdResolved), emissionModel=\(visibleEmissionModelName), synchAlpha=\(visibleSynchAlphaArg), visibleKappa=\(visibleKappaArg), coolAbsorption=(enabled=\(coolAbsorptionEnabled),dustToGas=\(coolDustToGasArg),dustKappaV=\(coolDustKappaVArg),dustBeta=\(coolDustBetaArg),dustTsub=\(coolDustTSubArg),dustTwidth=\(coolDustTWidthArg),gasKappa0=\(coolGasKappa0Arg),gasNuSlope=\(coolGasNuSlopeArg),clump=\(coolClumpStrengthArg)), exposureMode=\(exposureModeName), exposureEV=\(exposureEVArg), rayBundle=(requested=\(rayBundleEnabled),active=\(rayBundleActive),jacobian=\(rayBundleJacobianActive),jacStrength=\(rayBundleJacobianStrengthArg),clamp=\(rayBundleFootprintClampArg))"
    }
}
